# Generated by Django 2.2.5 on 2020-02-12 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('vol', models.IntegerField()),
                ('high', models.DecimalField(decimal_places=2, max_digits=4)),
                ('low', models.DecimalField(decimal_places=2, max_digits=4)),
                ('avg', models.DecimalField(decimal_places=2, max_digits=4)),
                ('open', models.DecimalField(decimal_places=2, max_digits=4)),
                ('close', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='StockChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('vol', models.IntegerField()),
                ('high', models.DecimalField(decimal_places=2, max_digits=4)),
                ('low', models.DecimalField(decimal_places=2, max_digits=4)),
                ('avg', models.DecimalField(decimal_places=2, max_digits=4)),
                ('open', models.DecimalField(decimal_places=2, max_digits=4)),
                ('close', models.DecimalField(decimal_places=2, max_digits=4)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Stock')),
            ],
        ),
    ]
