# Generated by Django 2.2.5 on 2020-02-26 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='watchedstocks',
            new_name='watchedStocks',
        ),
    ]
