# Generated by Django 2.2.5 on 2020-02-18 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200217_0400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='watchedBy',
            field=models.ManyToManyField(blank=True, related_name='watchedStocks', to='api.UserProfile'),
        ),
    ]
