# Generated by Django 2.2.5 on 2020-02-20 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200220_2216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockchange',
            name='name',
        ),
    ]
