version: '3.7'

services:
    backend:
        build: 
            context: ./backend
            dockerfile: Dockerfile
        volumes:
            - backend_static_volume:/usr/src/app/static
        expose:
            - 8000
        env_file: 
            - ./backend/.env
        command: gunicorn saphire-backend.wsgi:application --bind 0.0.0.0:8000
        depends_on:
            - db

    db:
        image: postgres:12-alpine
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        env_file: 
            - ./postgres/.env

    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
            args:
                - API_SERVER=${ENV_API_SERVER}
        volumes:
            - frontend_static_volume:/usr/src/app/build/static
        expose:
            - 3000
        env_file:
            - .env
        command: serve -s build -l 3000
        depends_on:
            - backend

    nginx:
        restart: always
        build: ./nginx
        volumes:
            - backend_static_volume:/usr/src/app/backend_files/static
            - frontend_static_volume:/usr/src/app/frontend_files/static
        ports:
            - 80:80
        depends_on:
            - frontend

volumes:
    postgres_data:
    backend_static_volume:
    frontend_static_volume: