# Generated by Django 3.0.3 on 2020-04-14 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='watchedStocks',
            field=models.ManyToManyField(blank=True, related_name='watchedBy', to='api.Company'),
        ),
    ]
