# Generated by Django 3.1 on 2021-06-10 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='user',
            name='watchedStocks',
        ),
        migrations.DeleteModel(
            name='StockChange',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
